### ISSUE TITLE
1.0.1版本的插件元数据好像写错了（？

### ISSUE THREAD

**Issue by OptiJava** [Aimerny/PlayerLastPlay#1]
![image](https://user-images.githubusercontent.com/106148777/235274066-e65b9ed4-7771-4bd3-adb7-5cd84e801c2e.png)

version 应当改成1.0.1，如果1.0.1版本的插件元数据被写成1.0.0的话，会导致插件管理器反复更新插件（反正我出现了这个情况

另外链接好像也写错了（

**Comment by Aimerny** [comment]
> ![image](https://user-images.githubusercontent.com/106148777/235274066-e65b9ed4-7771-4bd3-adb7-5cd84e801c2e.png)
> 
> version 应当改成1.0.1，如果1.0.1版本的插件元数据被写成1.0.0的话，会导致插件管理器反复更新插件（反正我出现了这个情况
> 
> 另外链接好像也写错了（

11，源代码已经改了，release忘记改了
