### ISSUE TITLE
格式不对（？

### ISSUE THREAD

**Issue by OptiJava** [Aimerny/PlayerLastPlay#2]
打了`!!plp list`之后是这样的
![image](https://github.com/Aimerny/playerLastPlay/assets/106148777/9ce64817-5d7e-4cca-8519-e37effc516a9)
可能格式出问题了？

**Comment by OptiJava** [comment]
还是WindTerm的问题（？

**Comment by Aimerny** [comment]
> 还是WindTerm的问题（？

看样子是测试代码被打进去了？我修下
